[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "soc-analyst-agent"
version = "0.1.0"
description = "Zero-Trust Security Pipeline Built on Google Cloud"
readme = "README.md"
requires-python = ">=3.11"

[tool.setuptools.packages.find]
where = ["."]
